# Generated by Django 4.0 on 2022-08-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enviar_Email_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
